import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


import SelectStock from "../components/SelectStock"


export default function Home() {
  return (
    
    <div>
      <Head>
        <title>Allocation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
      <div className="container mx-auto">
        <h1 className="text-3xl font-bold">Chọn danh mục</h1>
        <SelectStock />
      </div>
  
           
            
            
            
              

        
      

      
    </div>
    
  )
}
